### ISSUE TITLE
panic: unexpected status 400 Bad Request from log server

### ISSUE THREAD

**Issue by jonaslejon** [grahamedgecombe/ct-submit#1]
je@https:~/ct-submit-master$ ./ct-submit-master ct.googleapis.com/pilot <../https.pem >https.sct
panic: unexpected status 400 Bad Request from log server

goroutine 1 [running]:
runtime.panic(0x605b80, 0xc210233e90)
    /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.main()
    /home/je/ct-submit-master/ct-submit.go:153 +0x4f5

goroutine 4 [syscall]:
runtime.goexit()
    /usr/lib/go/src/pkg/runtime/proc.c:1394

goroutine 5 [chan receive]:
net/http.(_persistConn).readLoop(0xc210060380)
    /usr/lib/go/src/pkg/net/http/transport.go:778 +0x68f
created by net/http.(_Transport).dialConn
    /usr/lib/go/src/pkg/net/http/transport.go:528 +0x607

goroutine 6 [select]:
net/http.(_persistConn).writeLoop(0xc210060380)
    /usr/lib/go/src/pkg/net/http/transport.go:791 +0x271
created by net/http.(_Transport).dialConn
    /usr/lib/go/src/pkg/net/http/transport.go:529 +0x61e

**Comment by grahamedgecombe** [comment]
Can you upload the `https.pem` file that you're trying to submit? Will be helpful to diagnose the issue.

**Comment by grahamedgecombe** [comment]
I've just pushed e4d71c7 which will print the error message returned by the log server. I suspect there's probably a problem with the certificate chain you are trying to submit (e.g. not in the correct order, missing intermediate certificates or a root that's not accepted by Google's log server).

**Comment by jonaslejon** [comment]
Thanks for the update! The certificate needs an intermediate certificate and thats probably why it fails:

unexpected status 400 Bad Request from log server:

{
  "error_message": "Root certificate is not trusted.",
  "success": false
}

**Comment by grahamedgecombe** [comment]
Okay, closing this as I'm assuming adding the intermediate(s) to the chain in the correct order will work (feel free to re-open if not). It's not a goal of this program to create the chain automatically (as it'd be quite complicated!) nginx requires the intermediates/leaf to be present and in the correct order as well anyway.
