### ISSUE TITLE
submit of StartCom to log.certly.io fails

### ISSUE THREAD

**Issue by sezuan** [grahamedgecombe/ct-submit#2]
I was able to submit a StartCom EV certificate to the following logs:
- ct.googleapis.com/*
- ctlog.api.venafi.com
- ct.wosign.com

When I tried to submit the certificate to log.certly.io I got the following error:

```
panic: Post https://log.certly.io/ct/v1/add-chain: x509: certificate signed by unknown authority
       (possibly because of "x509: cannot verify signature: algorithm unimplemented" while
       trying to verify candidate authority certificate "COMODO RSA Certification Authority")
```

Uploading the certificate with [`ct`](https://github.com/google/certificate-transparency) was successfull.

**Comment by grahamedgecombe** [comment]
Which version of Go are you using?

**Comment by sezuan** [comment]
```
go version go1.2.1 linux/amd64
```

**Comment by grahamedgecombe** [comment]
I think this may be the same problem as http://bridge.grumpy-troll.org/2014/05/golang-tls-comodo/

Does adding `import _ "crypto/sha512"` to `ct-submit.go` fix it? If so I'll add this workaround to master.

**Comment by sezuan** [comment]
That works for me. Thanks!
