### ISSUE TITLE
Default Scheme Parsing Broken

### ISSUE THREAD

**Issue by injust** [grahamedgecombe/ct-submit#3]
The parsing of the URL to set the default scheme to https:// is broken.

Target: https://ct.googleapis.com/aviator
If you include the https://, it tries to submit to https://ct.googleapis.com/ct/v1/add-chain
If you remove the https://, it tries to submit to https:///ct/v1/add-chain

**Comment by grahamedgecombe** [comment]
Should be fixed in d469d9ced8728b89fad7084d7c41d3ff934d6700

**Comment by injust** [comment]
Partially broken, but usable.
If the certificate log has a path, e.g. in `ct.googleapis.com/aviator`, it must end with a `/` or else the path will be stripped.

For example: `ct.googleapis.com/pilot/` and `https://ct.googleapis.com/pilot/` work, but without the trailing slash, it will request to `https:/ct.googleapis.com/ct/v1/add-chain` (the `/pilot/` is stripped out).

**Comment by grahamedgecombe** [comment]
this should be fixed as well now
